version: '3.8'
services:
  web:
    build: ./src
    ports: [ "5050:5000" ]
    environment:
      - MSSQL_HOST=db
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=YourStrong@Passw0rd
      - MSSQL_DATABASE=searchdb
    depends_on:
      db:
        condition: service_healthy
    networks: [ sqli-net ]

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [ sqli-net ]

networks:
  sqli-net:
    driver: bridge
