version: '3.8'

services:
  web:
    build: ./src
    ports:
      - "5002:5000"
    environment:
      - DATABASE_URL=postgresql://app_user:app_password@db:5432/newsportal
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sqli-net

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=newsportal
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user -d newsportal" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sqli-net

networks:
  sqli-net:
    driver: bridge
