version: '3.8'
services:
  web:
    build: ./src
    ports: [ "5037:5000" ]
    environment:
      - MSSQL_HOST=db
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=YourStr0ng!Passw0rd
      - MSSQL_DATABASE=reporting
    depends_on:
      db:
        condition: service_healthy
    networks: [ sqli-net ]

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStr0ng!Passw0rd
      - MSSQL_PID=Developer
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    entrypoint: /bin/bash
    command: >
      -c " /opt/mssql/bin/sqlservr & sleep 30 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStr0ng!Passw0rd' -d master -i /docker-entrypoint-initdb.d/init.sql -C && wait "
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStr0ng!Passw0rd" -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks: [ sqli-net ]

networks:
  sqli-net:
    driver: bridge
